apiVersion: v1
kind: Service
metadata:
  name: traefik

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: web
      port: 8000
    - protocol: TCP
      name: admin
      port: 8080
    - protocol: TCP
      name: websecure
      port: 8443
    - protocol: TCP
      name: prometheus
      port: 8082
    - protocol: TCP
      name: redis
      port: 6379
  selector:
    app: traefik
