apiVersion: v1
kind: Service
metadata:
  name: whoami

spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: whoami
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  labels:
    app: whoami

spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: containous/whoami
          ports:
            - name: web
              containerPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroute
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`172.21.92.146`) && PathPrefix(`/whoami`)
    kind: Rule
    priority: 1
    middlewares:
      - name: test-auth
    services:
    - name: whoami
      port: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-ingress
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: whoami.kong.slave03.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: whoami
          servicePort: 80
